// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbyi1XDbooRjhG_LxZdHsYM0dXihmOhEgR1qtt3UguBh8pzUEF7BAUbP3I4A_iXRH4ig/exec";
